SELECT DISTINCT
ENC.PAT_ENC_CSN_ID AS 'ENC ID'
, PAT.PAT_MRN_ID AS 'MRN ID'
, DEP.SPECIALTY AS 'Specialty'
, LOC.LOC_NAME AS 'Location'
, DEP.DEPARTMENT_ID AS 'Department ID'
, DEP.DEPARTMENT_NAME AS 'Department.'
, SER.PROV_NAME AS 'Provider'
, SER.PROV_ID AS 'PROV ID'
, CAST( ENC.CONTACT_DATE AS DATE )      AS 'Contact Date'
, PRC.PRC_ID AS 'Visit Type ID'
, PRC.PRC_NAME AS 'Visit Type'
, VEC.AGE AS 'Age'
, ZCS.NAME AS 'Sex'
, ZCE.NAME AS 'Ethnicity.'
, ZCR.NAME AS 'Race.'
FROM PAT_ENC ENC


INNER JOIN   V_PAT_ENC            VEC    ON ENC.PAT_ENC_CSN_ID = VEC.PAT_ENC_CSN_ID
INNER JOIN   V_SCHED_APPT         APT    ON ENC.PAT_ENC_CSN_ID = APT.PAT_ENC_CSN_ID
INNER JOIN   PATIENT              PAT    ON ENC.PAT_ID = PAT.PAT_ID
LEFT  JOIN   PATIENT_RACE         PTR    ON PAT.PAT_ID = PTR.PAT_ID AND PTR.LINE = 1
LEFT  JOIN   CLARITY_PRC          PRC    ON ENC.APPT_PRC_ID = PRC.PRC_ID
LEFT  JOIN   CLARITY_SER          SER    ON ENC.VISIT_PROV_ID = SER.PROV_ID
LEFT  JOIN   CLARITY_DEP          DEP    ON ENC.DEPARTMENT_ID = DEP.DEPARTMENT_ID
LEFT  JOIN   CLARITY_LOC          LOC    ON DEP.REV_LOC_ID = LOC.LOC_ID
LEFT  JOIN   CLARITY_EMP          EMP    ON APT.APPT_CANC_USER_ID = EMP.USER_ID
LEFT  JOIN   ZC_SEX               ZCS    ON PAT.SEX_C = ZCS.RCPT_MEM_SEX_C
LEFT  JOIN   ZC_LANGUAGE          ZCL    ON PAT.LANGUAGE_C = ZCL.LANGUAGE_C
LEFT  JOIN   ZC_ETHNIC_GROUP      ZCE    ON PAT.ETHNIC_GROUP_C = ZCE.ETHNIC_GROUP_C
LEFT  JOIN   ZC_APPT_STATUS       ZCA    ON ENC.APPT_STATUS_C = ZCA.APPT_STATUS_C
LEFT  JOIN   ZC_PATIENT_RACE      ZCR    ON PTR.PATIENT_RACE_C = ZCR.PATIENT_RACE_C


WHERE YEAR(ENC.CONTACT_DATE) >= 2020 
AND   ENC.APPT_STATUS_C = 2
AND   DEP.SERV_AREA_ID = 55 --   ONLY  SACHS
AND   ZCA.NAME IS NOT NULL